//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KartingCupStandings
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseEntities : DbContext
    {
        public DatabaseEntities()
            : base("name=DatabaseEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ClassPointSystem> ClassPointSystems { get; set; }
        public virtual DbSet<Cup> Cups { get; set; }
        public virtual DbSet<Driver> Drivers { get; set; }
        public virtual DbSet<PointSystem> PointSystems { get; set; }
        public virtual DbSet<Race> Races { get; set; }
        public virtual DbSet<RaceResult> RaceResults { get; set; }
        public virtual DbSet<Season> Seasons { get; set; }
        public virtual DbSet<Standin> Standins { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
        public virtual DbSet<TeamDriver> TeamDrivers { get; set; }
        public virtual DbSet<ClassType> ClassTypes { get; set; }
    }
}
