//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KartingCupStandings
{
    using System;
    using System.Collections.Generic;
    
    public partial class RaceResult
    {
        public int Id { get; set; }
        public int RaceId { get; set; }
        public Nullable<int> DriverId { get; set; }
        public int Position { get; set; }
        public int ClassTypeId { get; set; }
    
        public virtual ClassType ClassType { get; set; }
    }
}
